name: messgo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.15.0
  firebase_auth: ^6.7.0
  cloud_firestore: ^6.10.0
  google_maps_flutter: ^2.18.2
  geolocator: ^14.1.1
  geocoding: ^5.0.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.4.2
  flutter_riverpod: ^3.4.3
  dio: ^5.11.1
  shared_preferences: ^2.5.5
  image_picker: ^1.2.3
  flutter_rating_bar: ^4.0.1
  supabase_flutter: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
